name: Hello testing
# This workflow will be triggered by a push to master.

on:
  push:
    branches: [ master ]

jobs:
  build-and-run:
    name: Build and run

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Build Code
        run: echo Hello at `date` from `pwd`
      - name: Multi-line script
        run: |
          echo First line
          echo Second line

